import inquirer from "inquirer";
const currency = {
    UsDollar_USD: 1,
    Euro_EUR: 0.94,
    PakistaniRupee_PKR: 278.70,
    OmaniRial_OMR: 0.39,
    IranianRial_IRR: 150.29,
    BaritishPound_GBP: 0.81,
    CanadianDollar_CAD: 1.37,
    AustralianDollar_AUD: 1.57,
    JapaneseYen_JPY: 154.61,
    IndiaRupee_IND: 83.36,
    NewZealandDollar_NZD: 1.69,
    SwissFranc_CHF: 0.91,
    SouthAfricanRand_ZAR: 19.10,
    RussianRuble_RUB: 93.07,
    BulgarianLev_BGN: 1.84,
    SingaporeDollar_SGD: 1.36,
    HongKongDollar_HKD: 7.83,
    SwedishKrona_SEK: 1.92,
    ThaiBaht_THB: 37.01,
    HungarianForint_HUF: 369.37,
    ChineseYuanRenminbi_CNY: 7.24,
    NorwegianKrone_NOK: 11.03,
    MexicanPesO_MXN: 17.06,
    DanishKrone_DKK: 7.00,
    MalausianRinggit_MYR: 4.78,
    PolishZloty_PLN: 4.05,
    BrazilianReal_BRL: 5.21,
    PhilippinePeso_PHP: 57.57,
    IndonesianRupiah_IDR: 16238.66,
    CzechKoruna_CZK: 23.69,
    EmiratiDirham_AED: 3.69,
    TaiwanNewDollar_TWN: 32.68,
    SouthKoreanWon_KRW: 1380.63,
    ArgentinePeso_ARS: 871.25,
    ChileanPeso_CLP: 959.14,
    EgyptianPound_EGP: 48.40,
    TurkishLira_TRY: 32.60,
    RomanianLeu_RON: 4.67,
    SaudiArabianRiyal_SAR: 3.75,
    colombianPeso_COP: 3908.77,
    IraqiDinar_IQD: 1308.63,
    GoldOunce_XAU: 0.000424,
    FijianDollar_FJD: 2.27,
    KuwaitiDinar_KWD: 0.31,
    BosnianConvertibleMark_BAM: 1.84,
    IcelandicKrona_ISK: 141.27,
    MoroccanDirham_MAD: 10.15,
    VietnameseDong_VND: 25379.75,
    JamaicanDollar_JMD: 155.56,
    JordanianDinar_JOD: 0.71,
    DominicanPeso_DOP: 58.88,
    PeruvianSol_PEN: 3.68,
    CostaRicanColon_CRC: 500.58,
    BahrainiDinar_BHD: 0.38,
    BangladeshiTaka_BDT: 109.67,
    AlgerianDinar_DZD: 134.67,
    KenyanShilling_KES: 131.42,
    SilverOunce_XAG: 0.04,
    SriLankanRupee_LKR: 301.85,
    QatariRiyal_QAR: 3.64,
    TunisianDinar_TND: 3.16,
    TrinidadianDollar_TTD: 6.78,
    ZambianKwacha_ZMK: 0.9,
    ZambianKwachaa_ZMW: 25.84,
    BarbadianOrBajanDollar_BBD: 2.00,
    NigerianNari_NGN: 1150.92,
    LebanesePound_LBP: 91987.12,
    MauritianRupee_MUR: 46.50,
    PlatinumOunce_XPT: 0.0011,
    BahamianDollar_BSD: 1.00,
    AlbanianLek_ALL: 94.77,
    UruguayanPeso_UYU: 38.56,
    BermudianDollar_BMD: 1.00,
    LatvianLat_LVL: 0.66,
    UkrainianHryvnia_UAH: 39.75,
    GuatemalanQuetzal_GTQ: 7.76,
    BolivianBoliviano_BOB: 6.91,
    CubanPeso_CUP: 23.95,
    ParaguayanGuarani_PYG: 7392.90,
    HonduranLempira_HNL: 24.64,
    LithuanianLitas_LTL: 3.24,
    NicaraguanCordoba_NIO: 36.91,
    SerbianDinar_RSD: 109.93,
    NepaleseRupee_NPR: 133.47,
    HaitianGorde_HTG: 132.48,
    PanamanianBalboa_PAB: 1.00,
    SalvadoranColon_SVC: 8.75,
    GuyaneseDollar_GYD: 208.44,
    CaymanianDollar_KYD: 0.82,
    TanzanianShilling_TZS: 2579.99,
    CapeVerdeanEscudo_CVE: 103.44,
    FalklandIslandPound_FKP: 0.81,
    UgandanShilling_UGX: 3816.02,
    MalagasyAriary_MGA: 4404.00,
    GeorgianLari_GEL: 2.68,
    EthiopianBirr_ETB: 57.11,
    MoldovanLeu_MDL: 17.86,
    NiVaunatuVatu_VUV: 121.99,
    SyrianPund_SYP: 13001.80,
    BruneianDollar_BND: 1.36,
    CambodianRiel_KHR: 4065.39,
    NamibianDollar_NAD: 19.18,
    MacedonianDenar_MKD: 57.84,
    AngolanKwanza_AOA: 844.16,
    PapuaNewGuineanKina_PGK: 3.80,
    BurmeseKyat_MMK: 2096.38,
    LazaljstamoTenge_KZT: 445.78,
    MacauPataca_MOP: 8.07,
    MozambicanMetical_MZN: 63.99,
    LibyanDinar_LYD: 4.87,
    GuineanFrance_GNF: 8597.13,
    BelarusianRublee_BYR: 32700.20,
    GambianDalasi_GMD: 67.90,
    ArubanFlorin_AWG: 1.79,
    ArmenianDram_AMD: 390.87,
    YemeniRial_YER: 250.36,
    LaoKip_LAK: 21456.61,
    SamoanTala_WST: 2.79,
    MalawianKwacha_MWK: 1739.42,
    NorthKoreanWom_KPW: 899.97,
    BurundianFrance_BIF: 2874.30,
    DijiboutianFrance_DJF: 177.71,
    MongolianTughrik_MNT: 3394.30,
    UzbekistaniSom_UZS: 12668.93,
    TonganPaanga_TOP: 2.40,
    SeychelloisRupee_SCR: 14.12,
    KyrgyzstaniSom_KGS: 88.91,
    BhutaneseNgultrum_BTN: 83.38,
    SolomanIslanderDolar_SBD: 8.31,
    GibraltarPound_GIP: 0.81,
    RwandanFrance_RWF: 1291.70,
    CongoleseFrance_CDF: 2799.95,
    MaldivianRufiyaa_MVR: 15.38,
    MauritanianOuguiya_MRO: 396.96,
    EritreanNakfa_ERN: 15.00,
    SomaliShilling_SOS: 570.97,
    SwaziLilangeni_SZL: 19.18,
    TajikistaniSomoni_TJS: 10.95,
    LiberianDollar_LRD: 192.14,
    BasothoLoti_LSL: 19.18,
    SaintHelenianPound_SHP: 0.81,
    SaoTomeanDobra_STD: 23014.96,
    ComorianFrance_KMF: 461.74,
    SeborganLuigino_SPL: 0.17,
    TurkmenistaniManat_TMT: 3.49,
    SurinemeseDollar_SRD: 34.44,
    IsleOfManPound_IMP: 0.81,
    JerseyPund_JEP: 0.81,
    TuvaluanDollar_TVD: 1.55,
    GuernseyPound_GGP: 0.81,
    AfghanAfghani_AFN: 72.24,
    AzerbaijanManat_AZN: 1.70,
    BelizeanDollar_BZD: 2.02,
    CubanConvertiblePeso_CUC: 1.00,
    GhanainaCedi_GHS: 13.44,
    SudanesePund_SDG: 585.51,
    VenezuelanBolivar_VEF: 3629935.07,
    PalladiumOunce_XPD: 0.000985,
    BitCoin_XBT: 0.000015,
};
let answer = await inquirer.prompt([
    {
        name: "from",
        message: "Enter from Currency",
        type: "list",
        choices: ["UsDollar_USD", "Euro_EUR", "PakistaniRupee_PKR", "OmaniRial_OMR", "IranianRial_IRR", "BaritishPound_GBP", 'CanadianDollar_CAD', 'AustralianDollar_AUD', "JapaneseYen_JPY", "IndiaRupee_IND", "NewZealandDollar_NZD", "SwissFranc_CHF", "SouthAfricanRand_ZAR", "RussianRuble_RUB", "BulgarianLev_BGN", "SingaporeDolla", "HongKongDollar_HKD", "SwedishKrona_SEK", "ThaiBaht_THB", "HungarianForint_HUF", 'ChineseYuanRenminbi_CNY', "NorwegianKrone_NOK", "MexicanPesO_MXN", "DanishKrone_DKK", "MalausianRinggit_MYR", "PolishZloty_PLN", 'BrazilianReal_BRL', "PhilippinePeso_PHP", "IndonesianRupiah_IDR", "CzechKoruna_CZK", "EmiratiDirham_AED", "TaiwanNewDollar_TWN", "SouthKoreanWon_KRW", "ArgentinePeso_ARS", "ChileanPeso_CLP", "EgyptianPound_EGP", "TurkishLira_TRY", "RomanianLeu_RON", "SaudiArabianRiyal_SAR", "colombianPeso_COP", "IraqiDinar_IQD", "GoldOunce_XAU", "FijianDollar_FJD", "KuwaitiDinar_KWD", "BosnianConvertibleMark_BAM", "IcelandicKrona_ISK", "MoroccanDirham_MAD", "VietnameseDong_VND", "JamaicanDollar_JMD", "JordanianDinar_JOD", "DominicanPeso_DOP", "PeruvianSol_PEN", "CostaRicanColon_CRC", "BahrainiDinar_BHD", "BangladeshiTaka_BDT", "AlgerianDinar_DZD", "KenyanShilling_KES", "SilverOunce_XAG", "SriLankanRupee_LKR", "QatariRiyal_QAR", "TunisianDinar_TND", "TrinidadianDollar_TTD", "ZambianKwacha_ZMK", "ZambianKwachaa_ZMW", "BarbadianOrBajanDollar_BBD", "NigerianNari_NGN", "LebanesePound_LBP", "MauritianRupee_MUR", "PlatinumOunce_XPT", "BahamianDollar_BSD", "AlbanianLek_ALL", "UruguayanPeso_UYU", "BermudianDollar_BMD", 'UkrainianHryvnia_UAH', 'GuatemalanQuetzal_GTQ', 'BolivianBoliviano_BOB', 'CubanPeso_CUP', 'ParaguayanGuarani_PYG', 'HonduranLempira_HNL', 'LithuanianLitas_LTL', 'NicaraguanCordoba_NIO', 'SerbianDinar_RSD', "NepaleseRupeeNPR", 'HaitianGorde_HTG', "PanamanianBalboa_PAB", "SalvadoranColon_SVC", "GuyaneseDollar_GYD", "CaymanianDollar_KYD", "TanzanianShilling_TZS", "ChineseYuanRenminbiOffshore_CNH", "FalklandIslandPound_FKP", "UgandanShilling_UGX", "MalagasyAriary_MGA", "GeorgianLari_GEL", "EthiopianBirr_ETB", "MoldovanLeu_MDL", "NiVaunatuVatu_VUV", "SyrianPund_SYP", "BruneianDollar_BND", "CambodianRiel_KHR", "NamibianDollar_NAD", "MacedonianDenar_MKD", "AngolanKwanza_AOA", "PapuaNewGuineanKina_PGK", "BurmeseKyat_MMK", "LazaljstamoTenge_KZT", "MacauPataca_MOP", "MozambicanMetical_MZN", "LibyanDinar_LYD", "GuineanFrance_GNF", "BelarusianRublee_BYR", 'GambianDalasi_GMD', 'ArubanFlorin_AWG', "ArmenianDram_AMD", "YemeniRial_YER", "LaoKip_LAK", "SamoanTala_WST", "MalawianKwacha_MWK", "NorthKoreanWom_KPW", "BurundianFrance_BIF", "DijiboutianFrance_DJF", "MongolianTughrik_MNT", "UzbekistaniSom_UZS", "TonganPaanga_TOP", "SeychelloisRupee_SCR", "KyrgyzstaniSom_KGS", 'BhutaneseNgultrum_BTN', "SolomanIslanderDolar_SBD", "GibraltarPound_GIP", "RwandanFrance_RWF", "CongoleseFrance_CDF", "MaldivianRufiyaa_MVR", "MauritanianOuguiya_MRO", "EritreanNakfa_ERN", "SomaliShilling_SOS", 'SwaziLilangeni_SZL', "TajikistaniSomoni_TJS", "LiberianDollar_LRD", "BasothoLoti_LSL", "SaintHelenianPound_SHP", "SaoTomeanDobra_STD", "ComorianFrance_KMF", "SeborganLuigino_SPL", "TurkmenistaniMnat_TMT", "SurinemeseDollar_SRD", "IsleOfManPound_IMP", "JerseyPund_JEP", "TuvaluanDollar_TVD", "GuernseyPound_GGP", "AfghanAfghani_AFN", "AzerbaijanManat_AZN", "BelizeanDollar_BZD", "CubanConvertiblePeso_CUC", "GhanainaCedi_GHS", "SudanesePund_SDG", "VenezuelanBolivar_VEF", "PalladiumOunce_XPD", "BitCoin_XBT"]
    },
    {
        name: "to",
        message: "Enter to Currency",
        type: "list",
        choices: ["UsDollar_USD", "Euro_EUR", "PakistaniRupee_PKR", "OmaniRial_OMR", "IranianRial_IRR", "BaritishPound_GBP", 'CanadianDollar_CAD', 'AustralianDollar_AUD', "JapaneseYen_JPY", "IndiaRupee_IND", "NewZealandDollar_NZD", "SwissFranc_CHF", "SouthAfricanRand_ZAR", "RussianRuble_RUB", "BulgarianLev_BGN", "SingaporeDolla", "HongKongDollar_HKD", "SwedishKrona_SEK", "ThaiBaht_THB", "HungarianForint_HUF", 'ChineseYuanRenminbi_CNY', "NorwegianKrone_NOK", "MexicanPesO_MXN", "DanishKrone_DKK", "MalausianRinggit_MYR", "PolishZloty_PLN", 'BrazilianReal_BRL', "PhilippinePeso_PHP", "IndonesianRupiah_IDR", "CzechKoruna_CZK", "EmiratiDirham_AED", "TaiwanNewDollar_TWN", "SouthKoreanWon_KRW", "ArgentinePeso_ARS", "ChileanPeso_CLP", "EgyptianPound_EGP", "TurkishLira_TRY", "RomanianLeu_RON", "SaudiArabianRiyal_SAR", "colombianPeso_COP", "IraqiDinar_IQD", "GoldOunce_XAU", "FijianDollar_FJD", "KuwaitiDinar_KWD", "BosnianConvertibleMark_BAM", "IcelandicKrona_ISK", "MoroccanDirham_MAD", "VietnameseDong_VND", "JamaicanDollar_JMD", "JordanianDinar_JOD", "DominicanPeso_DOP", "PeruvianSol_PEN", "CostaRicanColon_CRC", "BahrainiDinar_BHD", "BangladeshiTaka_BDT", "AlgerianDinar_DZD", "KenyanShilling_KES", "SilverOunce_XAG", "SriLankanRupee_LKR", "QatariRiyal_QAR", "TunisianDinar_TND", "TrinidadianDollar_TTD", "ZambianKwacha_ZMK", "ZambianKwachaa_ZMW", "BarbadianOrBajanDollar_BBD", "NigerianNari_NGN", "LebanesePound_LBP", "MauritianRupee_MUR", "PlatinumOunce_XPT", "BahamianDollar_BSD", "AlbanianLek_ALL", "UruguayanPeso_UYU", "BermudianDollar_BMD", 'UkrainianHryvnia_UAH', 'GuatemalanQuetzal_GTQ', 'BolivianBoliviano_BOB', 'CubanPeso_CUP', 'ParaguayanGuarani_PYG', 'HonduranLempira_HNL', 'LithuanianLitas_LTL', 'NicaraguanCordoba_NIO', 'SerbianDinar_RSD', "NepaleseRupeeNPR", 'HaitianGorde_HTG', "PanamanianBalboa_PAB", "SalvadoranColon_SVC", "GuyaneseDollar_GYD", "CaymanianDollar_KYD", "TanzanianShilling_TZS", "ChineseYuanRenminbiOffshore_CNH", "FalklandIslandPound_FKP", "UgandanShilling_UGX", "MalagasyAriary_MGA", "GeorgianLari_GEL", "EthiopianBirr_ETB", "MoldovanLeu_MDL", "NiVaunatuVatu_VUV", "SyrianPund_SYP", "BruneianDollar_BND", "CambodianRiel_KHR", "NamibianDollar_NAD", "MacedonianDenar_MKD", "AngolanKwanza_AOA", "PapuaNewGuineanKina_PGK", "BurmeseKyat_MMK", "LazaljstamoTenge_KZT", "MacauPataca_MOP", "MozambicanMetical_MZN", "LibyanDinar_LYD", "GuineanFrance_GNF", "BelarusianRublee_BYR", 'GambianDalasi_GMD', 'ArubanFlorin_AWG', "ArmenianDram_AMD", "YemeniRial_YER", "LaoKip_LAK", "SamoanTala_WST", "MalawianKwacha_MWK", "NorthKoreanWom_KPW", "BurundianFrance_BIF", "DijiboutianFrance_DJF", "MongolianTughrik_MNT", "UzbekistaniSom_UZS", "TonganPaanga_TOP", "SeychelloisRupee_SCR", "KyrgyzstaniSom_KGS", 'BhutaneseNgultrum_BTN', "SolomanIslanderDolar_SBD", "GibraltarPound_GIP", "RwandanFrance_RWF", "CongoleseFrance_CDF", "MaldivianRufiyaa_MVR", "MauritanianOuguiya_MRO", "EritreanNakfa_ERN", "SomaliShilling_SOS", 'SwaziLilangeni_SZL', "TajikistaniSomoni_TJS", "LiberianDollar_LRD", "BasothoLoti_LSL", "SaintHelenianPound_SHP", "SaoTomeanDobra_STD", "ComorianFrance_KMF", "SeborganLuigino_SPL", "TurkmenistaniMnat_TMT", "SurinemeseDollar_SRD", "IsleOfManPound_IMP", "JerseyPund_JEP", "TuvaluanDollar_TVD", "GuernseyPound_GGP", "AfghanAfghani_AFN", "AzerbaijanManat_AZN", "BelizeanDollar_BZD", "CubanConvertiblePeso_CUC", "GhanainaCedi_GHS", "SudanesePund_SDG", "VenezuelanBolivar_VEF", "PalladiumOunce_XPD", "BitCoin_XBT"]
    },
    {
        name: "amount",
        message: "Enter Amount",
        type: "number"
    }
]);
let fromAmount = currency[answer.from]; //exchange rate
let toAmount = currency[answer.to]; // exchage rate
let amount = answer.amount;
let baseAmount = amount / fromAmount; // USD base currency
let convertedAmount = baseAmount * toAmount;
console.log(convertedAmount);
